name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test-parse-world-forge:
    name: Data Files
    runs-on: ubuntu-latest
    steps:
    - uses: warp-core/endless-sky-test-parse@master

