name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  changed:
    name: Changed
    uses: ./.github/workflows/changes.yaml

  test-parse:
    name: Data Files
    runs-on: windows-2022
    if: ${{ needs.changed.outputs.workflows == 'true' || needs.changed.outputs.data_files == 'true' }}
    steps:
    - uses: warp-core/endless-sky-test-parse@master

